# NetSurf Frontend sources

FRONTEND_SOURCE_DIR := frontends/$(FRONTEND_TARGET)
FRONTEND_RESOURCES_DIR := frontends/$(FRONTEND_TARGET)/res

# Target Specific setup
include frontends/$(FRONTEND_TARGET)/Makefile

S_FRONTEND := $(addprefix frontends/$(FRONTEND_TARGET)/,$(S_FRONTEND))

INCLUDE_DIRS += frontends
