# ----------------------------------------------------------------------------
# Jotter-specific options
# ----------------------------------------------------------------------------

SLATE_JOTTER_RESOURCES := $(PREFIX)/share/slate/
SLATE_JOTTER_BIN := $(PREFIX)/bin/
SLATE_USE_RSVG := NO
SLATE_USE_NSSVG := AUTO
SLATE_USE_ROSPRITE := NO
SLATE_USE_HARU_PDF := NO
SLATE_FS_BACKING_STORE := YES

CFLAGS += -O2
