#
# NetSurf javascript source file inclusion
#
# Included by Makefile
#

include content/handlers/javascript/quickjs/Makefile

# Fetcher for javascript scheme is always required
S_JAVASCRIPT += fetcher.c
