[package]
name = "slate-rendering"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
dpi.workspace = true
headers.workspace = true
rustls.workspace = true
servo.workspace = true
slate-broadwebd.workspace = true
url.workspace = true

[dev-dependencies]
slate-broadwebd = { workspace = true, features = ["test-fixtures"] }

[lints]
workspace = true
