[package]
name = "slate-profile-sync"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[features]
local-preview-fixtures = ["slate-broadwebd/test-fixtures"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
slate-broadwebd.workspace = true
slate-routing.workspace = true
slate-storage.workspace = true

[dev-dependencies]
slate-broadwebd = { workspace = true, features = ["test-fixtures"] }

[lints]
workspace = true
